# Generated by Django 4.0.6 on 2022-07-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_total', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoComponente', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoComponente', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Altavoz',
            fields=[
                ('dispositivosalida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ordenapp.dispositivosalida')),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ordenapp.dispositivosalida',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('dispositivosalida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ordenapp.dispositivosalida')),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ordenapp.dispositivosalida',),
        ),
        migrations.CreateModel(
            name='PlacaBase',
            fields=[
                ('dispositivoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ordenapp.dispositivoentrada')),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ordenapp.dispositivoentrada',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('dispositivoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ordenapp.dispositivoentrada')),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ordenapp.dispositivoentrada',),
        ),
        migrations.CreateModel(
            name='Raton',
            fields=[
                ('dispositivoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ordenapp.dispositivoentrada')),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ordenapp.dispositivoentrada',),
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('dispositivoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ordenapp.dispositivoentrada')),
                ('cantidad', models.IntegerField()),
                ('costo', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ordenapp.dispositivoentrada',),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_costo_orden', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('computadoras', models.ManyToManyField(to='ordenapp.computadora')),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='altavoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.altavoz'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.monitor'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='placaBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.placabase'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='procesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.procesador'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='raton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.raton'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='teclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.teclado'),
        ),
    ]
