# Generated by Django 4.0.6 on 2022-07-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contadorComputadoras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('contadorMonitores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEntrada', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('contadorRatones', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEntrada', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('contadorTeclados', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contadorOrdenes', models.IntegerField()),
                ('computadoras', models.ManyToManyField(to='ordenapp.computadora')),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.monitor'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='raton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.raton'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='teclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenapp.teclado'),
        ),
    ]
