# Generated by Django 4.0.6 on 2022-07-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivoentrada',
            name='tipoComponente',
            field=models.CharField(choices=[('keyboard', 'teclado'), ('mouse', 'raton'), ('display', 'monitor'), ('speaker', 'altavoz'), ('motherboard', 'placa'), ('processor', 'procesador')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivosalida',
            name='tipoComponente',
            field=models.CharField(choices=[('keyboard', 'teclado'), ('mouse', 'raton'), ('display', 'monitor'), ('speaker', 'altavoz'), ('motherboard', 'placa'), ('processor', 'procesador')], max_length=50),
        ),
    ]
